name: "x2iot Hub"
version: "1.5.10"
slug: "x2iot"
description: "IoT Integration Platform - Satel Integra, MQTT i więcej"
url: "https://github.com/kroolik89/x2iot"
arch:
  - amd64
  - aarch64
init: false
startup: application
boot: auto
ports:
  "8356/tcp": 8356
ports_description:
  "8356/tcp": "x2iot Web Interface"
ingress: true
ingress_port: 8356
panel_icon: "mdi:chip"
panel_title: "x2iot Hub"
panel_admin: false
webui: "http://[HOST]:[PORT:8356]"
