/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const hydrate: () => void;
export const __wbg_intounderlyingbytesource_free: (a: number, b: number) => void;
export const intounderlyingbytesource_autoAllocateChunkSize: (a: number) => number;
export const intounderlyingbytesource_cancel: (a: number) => void;
export const intounderlyingbytesource_pull: (a: number, b: any) => any;
export const intounderlyingbytesource_start: (a: number, b: any) => void;
export const intounderlyingbytesource_type: (a: number) => number;
export const __wbg_intounderlyingsource_free: (a: number, b: number) => void;
export const intounderlyingsource_cancel: (a: number) => void;
export const intounderlyingsource_pull: (a: number, b: any) => any;
export const __wbg_intounderlyingsink_free: (a: number, b: number) => void;
export const intounderlyingsink_abort: (a: number, b: any) => any;
export const intounderlyingsink_close: (a: number) => any;
export const intounderlyingsink_write: (a: number, b: any) => any;
export const wasm_bindgen_1e354aaa153758e___convert__closures_____invoke___wasm_bindgen_1e354aaa153758e___JsValue__core_f0fd674eaa06beef___result__Result_____wasm_bindgen_1e354aaa153758e___JsError___true_: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen_1e354aaa153758e___convert__closures_____invoke___js_sys_736ee77576f6a6df___Function_fn_wasm_bindgen_1e354aaa153758e___JsValue_____wasm_bindgen_1e354aaa153758e___sys__Undefined___js_sys_736ee77576f6a6df___Function_fn_wasm_bindgen_1e354aaa153758e___JsValue_____wasm_bindgen_1e354aaa153758e___sys__Undefined_______true_: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen_1e354aaa153758e___convert__closures_____invoke___wasm_bindgen_1e354aaa153758e___JsValue______true_: (a: number, b: number, c: any) => void;
export const wasm_bindgen_1e354aaa153758e___convert__closures_____invoke___wasm_bindgen_1e354aaa153758e___JsValue______true__1_: (a: number, b: number, c: any) => void;
export const wasm_bindgen_1e354aaa153758e___convert__closures_____invoke___web_sys_a5dbd14d77720278___features__gen_CloseEvent__CloseEvent______true_: (a: number, b: number, c: any) => void;
export const wasm_bindgen_1e354aaa153758e___convert__closures_____invoke___wasm_bindgen_1e354aaa153758e___JsValue______true__1__4: (a: number, b: number, c: any) => void;
export const wasm_bindgen_1e354aaa153758e___convert__closures_____invoke___web_sys_a5dbd14d77720278___features__gen_CloseEvent__CloseEvent______true__5: (a: number, b: number, c: any) => void;
export const wasm_bindgen_1e354aaa153758e___convert__closures_____invoke_______true_: (a: number, b: number) => void;
export const wasm_bindgen_1e354aaa153758e___convert__closures_____invoke_______true__1_: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
